### PR TITLE
Switch deprecated hook_tabs to hook_tabset

### PR DESCRIPTION
**Pull request by colemanw**
Overview
-------
Switches hook implementation from deprecated to preferred hook.

Before
-----
Old hook used.

After
------
New hook used. No functional change.

### CODE REVIEW

**Comment by jaapjansma** [comment]
Am I right to assume that this PR makes the document extension only compatible with newer versions of civicrm? Is there a way in which we could keep the document extension backwards compatible?

**Comment by colemanw** [comment]
This "new" hook actually dates back to CiviCRM 4.4, so no, switching hooks alone does not break backwards compatibility (although if you want to keep 4.4 compatibility you would have to re-add the `snippet=1` from the url which I removed because it's not needed in 4.5+)

However I think the point is moot because you just merged 2 other PRs which definitely *do* break backwards compatibility. So the info.xml file needs to be updated to support 4.7+ only.

IMHO this is fine. This extension already has a stable release that works on older systems. People who don't want to upgrade their CiviCRM core shouldn't upgrade this extension either. For people who are on newer versions, they can have the newer feature in this extension that we are adding :)

**Comment by colemanw** [comment]
@jaapjansma I've updated the info.xml file in this PR

**Comment by jaapjansma** [comment]
I do think it is safe to drop 4.4 compatibility. Thanks.

**Pull request merged**
